@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE5ODQ0NTd9.iUY0oFmnPlm-d-Crjt4CyKhBp532mIDnd2ASHC0cEIA
@hostname = http://localhost:3000

### PRODUCTS INDEX
GET {{hostname}}/products?category=Damage

### PRODUCTS CREATE
POST {{hostname}}/products
Content-Type: application/json

{
  "name": "carzzz",
  "price": 3200,
  "image_url": "car.com",
  "description": "you sit in the car",
  "supplier_id": 1
}

### PRODUCTS SHOW
GET {{hostname}}/products/2

### PRODUCTS UPDATE
PATCH {{hostname}}/products/5
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "inventory": 20,
  "description": "For real, for real this time"
}

### PRODUCTS DESTROY
DELETE {{hostname}}/products/8

### Users create (signup)
POST {{hostname}}/users
Content-Type: application/json

{
  "name": "Ace",
  "email": "ace@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{hostname}}/sessions
Content-Type: application/json

{
  "email": "ace@gmail.com",
  "password": "password"
}

### Orders INDEX
GET {{hostname}}/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Orders create
POST {{hostname}}/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Orders SHOW
GET {{hostname}}/orders/2
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Carted Products Index
GET {{hostname}}/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Carted Products Create
POST {{hostname}}/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 5,
  "quantity": 1
}

### Carted Products Update/Destroy
PATCH {{hostname}}/carted_products/7
Content-Type: application/json
Authorization: Bearer {{jwt}}